# Prettier configuration
# https://prettier.io/docs/en/configuration.html
#
# Shared org-wide config. Individual repos can extend or override as needed.

printWidth: 100
tabWidth: 2
useTabs: false
endOfLine: lf

overrides:
  - files:
      - '*.yaml'
      - '*.yml'
    options:
      singleQuote: true
  - files:
      - '*.json'
    options:
      trailingComma: none
  - files:
      - '*.md'
    options:
      proseWrap: preserve
